### ISSUE TITLE
Will I be banned if I use this plugin to play games?

### ISSUE THREAD

**Issue by easonwang0** [everyonesdesign/Chess-Helper#14]
I've read the code and know it control pieces by JS. I've send an email to ask chess.com and lichess.org whether I can use JS to control the pieces. Chess.com haven't replied me yet while lichess warned me that players using it will be banned. 

So I worry about the risk of using this plugin. Did you communicate with Chess.com? @everyonesdesign

**Comment by everyonesdesign** [comment]
Hey, @easonwang0 !

Thank you for your question.

I haven't contacted Chess.com about the possibility of users ban. As a matter of fact, I cannot guarantee that you won't be blocked by Chess.com (it is indeed completely up to them). If you receive the response from them, I would be very interested to hear it, by the way.

In case if there will be any signals that Chess.com considers the extension usage rules violation I'll try to take measures as quickly as possible (up to the extension removal from store, if necessary); but, again, unfortunately, I cannot guarantee safety in this regard.

**Practical response**: I wrote this extension as I love keyboard navigation, and besides satisfying my need in that I also shared it with other people. I use the extension quite often and I haven't been blocked yet.

**Idealistic long-term vision**: currently ~260 people are using the extension on different platforms; I hope that at some stage I might bet enough users to make a case for Chess.com so they consider this functionality as core one and, maybe, implement something similar. I don't have high hopes for success though. But until then, I have to face all the risks of 3rd party extension (since Chess.com doesn't provide API for game actions).

**Comment by everyonesdesign** [comment]
I made a request to Chess.com about their plan to integrate such functionality.

Their response was:

> Hello!
> 
> You can certainly check in with our developer group here:
> https://www.chess.com/club/chess-com-developer-community
> 
> They'll be able to give you more API support and can interface with you about future updates. I know that in the past, the primary users of such an applications have been people trying to find interfaces to get their engines or bots to play on chess.com :/ However, it certainly does make our site more accessible!

Maybe I'll do it in the future to make sure I use API that isn't blocked by anti-cheat detection, however I'm not actually sure yet if there're any appropriate tools for that. For now, unfortunately, I cannot guarantee safety from being blocked.

I will close the issue as it is  a question, but not an issue with the extension itself.

**Comment by everyonesdesign** [comment]
Another useful source of information for this issue: a member of Chess.com staff mentioned that the extension usage is allowed: [link](https://www.chess.com/forum/view/general/keyboard-controls-for-chess-com-chess-com-keyboard-browser-extension?page=1#comment-53476882)

**Comment by leandwo** [comment]
I was automatically banned today after playing a blitz game while using this extension, with the violation cited as a breach of Chess.com’s fair play policy. I’ve submitted an appeal and plan to reference the link you shared when I receive a response. I’m really hoping that my account and daily games can be restored. 😭

It might be worth adding a cautionary note for users, about using the extension in live games

**Comment by everyonesdesign** [comment]
Good luck with your case @leandwo 

Just FYI, to correct myself about the link above, the statement was not just by any some staff member, but by [Eric](https://www.chess.com/member/erik) himself (a co-founder), hopefully his word will have some weight.

This is the first time I hear about such problems with this extension, please, let me know how it goes.

**Comment by leandwo** [comment]
@everyonesdesign they finally got back to me and reopened my account! Also, the guy said that they have taken steps to ensure I can "continue using the Chess.com Keyboard extension..." Here is the full response:

![Image](https://github.com/user-attachments/assets/cdfc432a-12b4-4b1c-b0ec-68a765fada8d)

**Comment by everyonesdesign** [comment]
Oh, I'm glad to hear that, congrats, and thank you for sharing!

**Comment by everyonesdesign** [comment]
Just to update on this: I also got banned for the extension use this month 😀

On 4th of February my account was blocked and I applied an appeal right away. I couldn't even access my posts on chess.com forum (e.g. [this one](https://www.chess.com/forum/view/general/keyboard-controls-for-chess-com-chess-com-keyboard-browser-extension))

On 8th of February the account was restored.
